/**
 * Horoscope Data
 * Contains daily horoscopes, profiles, and yearly forecasts for all 12 zodiac signs.
 */

const HOROSCOPE_DATA = [
    {
        name: "Aries",
        date: "Mar 21 - Apr 19",
        icon: "♈",
        element: "Fire",
        ruling_planet: "Mars",
        keywords: ["Courageous", "Determined", "Confident"],
        traits: "Aries loves to be number one, so it’s no surprise that these audacious rams are the first sign of the zodiac. Bold and ambitious, Aries dives headfirst into even the most challenging situations.",
        strengths: ["Courageous", "Determined", "Confident", "Enthusiastic", "Optimistic"],
        weaknesses: ["Impatient", "Moody", "Short-tempered", "Impulsive", "Aggressive"],
        compatibility: "**Most Compatible:** Leo, Sagittarius, Gemini, Aquarius.\n**Least Compatible:** Cancer, Capricorn.",
        horoscope: "Today is a day for action! Your energy levels are high, and you're ready to tackle any challenge that comes your way. Trust your instincts and take the lead.",
        yearly_forecast: "**2025 Overview:** This year brings a surge of energy and new beginnings. You will find yourself taking on leadership roles and initiating exciting projects.\n\n**Love:** Passion is in the air! Existing relationships deepen, while singles may find a spark in unexpected places.\n\n**Career:** Your ambition will be rewarded. Look out for a promotion or a new opportunity that aligns with your passions."
    },
    {
        name: "Taurus",
        date: "Apr 20 - May 20",
        icon: "♉",
        element: "Earth",
        ruling_planet: "Venus",
        keywords: ["Reliable", "Patient", "Practical"],
        traits: "Taurus is an earth sign represented by the bull. Like their celestial spirit animal, Taureans enjoy relaxing in serene, bucolic environments, surrounded by soft sounds, soothing aromas, and succulent flavors.",
        strengths: ["Reliable", "Patient", "Practical", "Devoted", "Responsible", "Stable"],
        weaknesses: ["Stubborn", "Possessive", "Uncompromising"],
        compatibility: "**Most Compatible:** Virgo, Capricorn, Cancer, Pisces.\n**Least Compatible:** Leo, Aquarius.",
        horoscope: "Take a moment to appreciate the finer things in life today. A slow and steady approach will yield the best results. Focus on stability and comfort.",
        yearly_forecast: "**2025 Overview:** Stability and growth are your themes for the year. Your hard work will pay off, bringing financial security and personal satisfaction.\n\n**Love:** Relationships require patience and understanding. meaningful connections will flourish.\n\n**Career:** Stick to your plans. Consistent effort will lead to long-term success."
    },
    {
        name: "Gemini",
        date: "May 21 - Jun 20",
        icon: "♊",
        element: "Air",
        ruling_planet: "Mercury",
        keywords: ["Adaptable", "Outgoing", "Intelligent"],
        traits: "Have you ever been so busy that you wished you could clone yourself just to get everything done? That’s the Gemini experience in a nutshell. Spontaneous, playful, and adorably erratic, Gemini is driven by its insatiable curiosity.",
        strengths: ["Gentle", "Affectionate", "Curious", "Adaptable", "Ability to learn quickly"],
        weaknesses: ["Nervous", "Inconsistent", "Indecisive"],
        compatibility: "**Most Compatible:** Libra, Aquarius, Aries, Leo.\n**Least Compatible:** Virgo, Pisces.",
        horoscope: "Your mind is buzzing with ideas today. It's a great time for communication, networking, and learning something new. Stay curious!",
        yearly_forecast: "**2025 Overview:** A year of intellectual expansion and social connection. You'll learn new skills and meet fascinating people.\n\n**Love:** Communication is key. Express your feelings openly to strengthen bonds.\n\n**Career:** Networking will open doors. Be ready to adapt to new opportunities."
    },
    {
        name: "Cancer",
        date: "Jun 21 - Jul 22",
        icon: "♋",
        element: "Water",
        ruling_planet: "Moon",
        keywords: ["Tenacious", "Imaginative", "Loyal"],
        traits: "Cancer is a cardinal water sign. Represented by the crab, this crustacean seamlessly weaves between the sea and shore, representing Cancer’s ability to exist in both emotional and material realms.",
        strengths: ["Tenacious", "Highly imaginative", "Loyal", "Emotional", "Sympathetic", "Persuasive"],
        weaknesses: ["Moody", "Pessimistic", "Suspicious", "Manipulative", "Insecure"],
        compatibility: "**Most Compatible:** Scorpio, Pisces, Taurus, Virgo.\n**Least Compatible:** Aries, Libra.",
        horoscope: "Trust your intuition today. You may feel more emotional than usual, so take time for self-care and connect with loved ones.",
        yearly_forecast: "**2025 Overview:** Emotional growth and deepening relationships are highlighted. You'll find comfort in home and family.\n\n**Love:** Vulnerability will bring you closer to your partner. Singles may find a soulmate.\n\n**Career:** Trust your gut instincts in business matters. Creative projects will thrive."
    },
    {
        name: "Leo",
        date: "Jul 23 - Aug 22",
        icon: "♌",
        element: "Fire",
        ruling_planet: "Sun",
        keywords: ["Creative", "Passionate", "Generous"],
        traits: "Roll out the red carpet, because Leo has arrived. Leo is represented by the lion, and these spirited fire signs are the kings and queens of the celestial jungle. They’re delighted to embrace their royal status: Vivacious, theatrical, and passionate.",
        strengths: ["Creative", "Passionate", "Generous", "Warm-hearted", "Cheerful", "Humorous"],
        weaknesses: ["Arrogant", "Stubborn", "Self-centered", "Lazy", "Inflexible"],
        compatibility: "**Most Compatible:** Aries, Sagittarius, Gemini, Libra.\n**Least Compatible:** Taurus, Scorpio.",
        horoscope: "Shine bright today! Your charisma is magnetic, drawing people towards you. Use your creativity to express yourself and inspire others.",
        yearly_forecast: "**2025 Overview:** It's your time to shine! Recognition and success are on the horizon. Embrace your creativity and leadership skills.\n\n**Love:** Romance is sizzling. Expect grand gestures and passionate encounters.\n\n**Career:** You'll be in the spotlight. Take credit for your achievements and aim high."
    },
    {
        name: "Virgo",
        date: "Aug 23 - Sep 22",
        icon: "♍",
        element: "Earth",
        ruling_planet: "Mercury",
        keywords: ["Loyal", "Analytical", "Kind"],
        traits: "Virgo is an earth sign historically represented by the goddess of wheat and agriculture, an association that speaks to Virgo’s deep-rooted presence in the material world. Virgos are logical, practical, and systematic in their approach to life.",
        strengths: ["Loyal", "Analytical", "Kind", "Hardworking", "Practical"],
        weaknesses: ["Shyness", "Worry", "Overly critical of self and others", "All work and no play"],
        compatibility: "**Most Compatible:** Taurus, Capricorn, Cancer, Scorpio.\n**Least Compatible:** Gemini, Sagittarius.",
        horoscope: "Focus on the details today. Your analytical skills are sharp, making it a perfect day for organizing, planning, and solving problems.",
        yearly_forecast: "**2025 Overview:** A year of productivity and self-improvement. Your attention to detail will lead to significant accomplishments.\n\n**Love:** Practical acts of service will show your love. Relationships built on mutual respect will thrive.\n\n**Career:** Your efficiency will be noticed. It's a good time to refine your skills and organize your workflow."
    },
    {
        name: "Libra",
        date: "Sep 23 - Oct 22",
        icon: "♎",
        element: "Air",
        ruling_planet: "Venus",
        keywords: ["Cooperative", "Diplomatic", "Gracious"],
        traits: "Libra is an air sign represented by the scales (interestingly, the only inanimate object of the zodiac), an association that reflects Libra's fixation on balance and harmony. Libra is obsessed with symmetry and strives to create equilibrium in all areas of life.",
        strengths: ["Cooperative", "Diplomatic", "Gracious", "Fair-minded", "Social"],
        weaknesses: ["Indecisive", "Avoids confrontations", "Will carry a grudge", "Self-pity"],
        compatibility: "**Most Compatible:** Gemini, Aquarius, Leo, Sagittarius.\n**Least Compatible:** Cancer, Capricorn.",
        horoscope: "Seek balance and harmony today. It's a great day for socializing, resolving conflicts, and appreciating beauty in your surroundings.",
        yearly_forecast: "**2025 Overview:** Relationships and partnerships take center stage. You'll find balance and harmony in your personal and professional life.\n\n**Love:** Romance is favored. New relationships may form, or existing ones will reach a new level of commitment.\n\n**Career:** Collaboration is key. Working with others will bring the best results."
    },
    {
        name: "Scorpio",
        date: "Oct 23 - Nov 21",
        icon: "♏",
        element: "Water",
        ruling_planet: "Pluto",
        keywords: ["Resourceful", "Brave", "Passionate"],
        traits: "Scorpio is one of the most misunderstood signs of the zodiac. Because of its incredible passion and power, Scorpio is often mistaken for a fire sign. In fact, Scorpio is a water sign that derives its strength from the psychic, emotional realm.",
        strengths: ["Resourceful", "Brave", "Passionate", "Stubborn", "A true friend"],
        weaknesses: ["Distrusting", "Jealous", "Secretive", "Violent"],
        compatibility: "**Most Compatible:** Cancer, Pisces, Virgo, Taurus.\n**Least Compatible:** Leo, Aquarius.",
        horoscope: "Dive deep into your passions today. Your intensity can be a powerful force for transformation. Don't be afraid to explore the mysteries of life.",
        yearly_forecast: "**2025 Overview:** A year of transformation and empowerment. You'll shed old habits and emerge stronger and more resilient.\n\n**Love:** Intense and passionate connections are likely. Trust and intimacy will be tested and strengthened.\n\n**Career:** Your determination will help you overcome obstacles. Research and investigation will yield rewards."
    },
    {
        name: "Sagittarius",
        date: "Nov 22 - Dec 21",
        icon: "♐",
        element: "Fire",
        ruling_planet: "Jupiter",
        keywords: ["Generous", "Idealistic", "Funny"],
        traits: "Represented by the archer, Sagittarius is always on a quest for knowledge. The last fire sign of the zodiac, Sagittarius launches its many pursuits like blazing arrows, chasing after geographical, intellectual, and spiritual adventures.",
        strengths: ["Generous", "Idealistic", "Great sense of humor"],
        weaknesses: ["Promises more than can deliver", "Very impatient", "Will say anything no matter how undiplomatic"],
        compatibility: "**Most Compatible:** Aries, Leo, Libra, Aquarius.\n**Least Compatible:** Virgo, Pisces.",
        horoscope: "Adventure awaits! Expand your horizons today, whether through travel, learning, or trying something new. Embrace your optimistic spirit.",
        yearly_forecast: "**2025 Overview:** Expansion and adventure are in store. You'll explore new territories, both physical and intellectual.\n\n**Love:** Freedom and fun are essential. You'll be attracted to partners who share your sense of adventure.\n\n**Career:** Opportunities for growth and learning abound. Teaching, publishing, or travel-related fields are favored."
    },
    {
        name: "Capricorn",
        date: "Dec 22 - Jan 19",
        icon: "♑",
        element: "Earth",
        ruling_planet: "Saturn",
        keywords: ["Responsible", "Disciplined", "Self-control"],
        traits: "The last earth sign of the zodiac, Capricorn is represented by the sea goat, a mythological creature with the body of a goat and the tail of a fish. Accordingly, Capricorns are skilled at navigating both the material and emotional realms.",
        strengths: ["Responsible", "Disciplined", "Self-control", "Good managers"],
        weaknesses: ["Know-it-all", "Unforgiving", "Condescending", "Expecting the worst"],
        compatibility: "**Most Compatible:** Taurus, Virgo, Scorpio, Pisces.\n**Least Compatible:** Aries, Libra.",
        horoscope: "Focus on your goals and ambitions today. Your discipline and hard work will pay off. Take a structured approach to your tasks.",
        yearly_forecast: "**2025 Overview:** Hard work and discipline will lead to significant achievements. You'll build a solid foundation for the future.\n\n**Love:** Commitment and stability are important. You'll value a partner who supports your ambitions.\n\n**Career:** Professional success is within reach. Your leadership skills will be recognized."
    },
    {
        name: "Aquarius",
        date: "Jan 20 - Feb 18",
        icon: "♒",
        element: "Air",
        ruling_planet: "Uranus",
        keywords: ["Progressive", "Original", "Independent"],
        traits: "Despite the \"aqua\" in its name, Aquarius is actually the last air sign of the zodiac. Aquarius is represented by the water bearer, the mystical healer who bestows water, or life, upon the land. Accordingly, Aquarius is the most humanitarian astrological sign.",
        strengths: ["Progressive", "Original", "Independent", "Humanitarian"],
        weaknesses: ["Runs from emotional expression", "Temperamental", "Uncompromising", "Aloof"],
        compatibility: "**Most Compatible:** Gemini, Libra, Aries, Sagittarius.\n**Least Compatible:** Taurus, Scorpio.",
        horoscope: "Embrace your uniqueness today. Your innovative ideas can lead to positive change. Connect with your community and fight for what you believe in.",
        yearly_forecast: "**2025 Overview:** Innovation and social change are your themes. You'll be inspired to make a difference in the world.\n\n**Love:** Intellectual connection is vital. You'll be drawn to unconventional and free-spirited partners.\n\n**Career:** Collaborative projects and technology-related fields will thrive. Don't be afraid to think outside the box."
    },
    {
        name: "Pisces",
        date: "Feb 19 - Mar 20",
        icon: "♓",
        element: "Water",
        ruling_planet: "Neptune",
        keywords: ["Compassionate", "Artistic", "Intuitive"],
        traits: "Pisces, a water sign, is the last constellation of the zodiac. It's symbolized by two fish swimming in opposite directions, representing the constant division of Pisces' attention between fantasy and reality.",
        strengths: ["Compassionate", "Artistic", "Intuitive", "Gentle", "Wise", "Musical"],
        weaknesses: ["Fearful", "Overly trusting", "Sad", "Desire to escape reality"],
        compatibility: "**Most Compatible:** Cancer, Scorpio, Taurus, Capricorn.\n**Least Compatible:** Gemini, Sagittarius.",
        horoscope: "Let your imagination soar today. Your intuition is strong, so listen to your inner voice. Express your creativity through art or music.",
        yearly_forecast: "**2025 Overview:** A year of spiritual growth and creativity. You'll feel more connected to your intuition and the universe.\n\n**Love:** Romance is dreamy and idealistic. You'll seek a soul connection with your partner.\n\n**Career:** Artistic and healing professions are favored. Trust your intuition to guide your career path."
    }
];
